FROM jenkins/jenkins:latest

USER root

RUN apt-get update && \
   apt-get install -y --no-install-recommends \
   vim \
   ssh \
   iputils-ping \
   iproute2 \
   openssh-client \
   wget
   

RUN echo "root:12345" | chpasswd 
	
RUN service ssh start
#setup ssh
RUN mkdir /var/jenkins_home/.ssh/ && \ 
	ssh-keygen -t rsa -C "12345" -m PEM -P "" -f /var/jenkins_home/.ssh/id_rsa

#CMD bash


#eval "$(ssh-agent -s)"
#ssh-add /var/jenkins_home/.ssh/id_rsa
#ssh-copy-id -i /var/jenkins_home/.ssh/id_rsa.pub root@172.20.0.10


